# https://goreleaser.com/customization/templates/
version: 2
builds:
  - goos:
      - linux
      - darwin
      # - windows
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "ginapp/conf.BuildVersion={{.Version}}"
      - -X "main.GoVersion={{.Env.GOVERSION}}"

    env:
      - CGO_ENABLED=1 # default is 1
archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
