# https://goreleaser.com/customization/templates/
builds:
  - goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "ginapp/conf.BuildVersion={{.Version}}"
      - -X "main.GoVersion={{.Env.GOVERSION}}"

    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
